{
 "title": "Kubernetes Cluster Alerts",
 "description": "Dashboard listing cluster resource specific alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All Alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table",
   "gridPos": { "h": 20, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "labelSelector": "alertname,description,summary", "target": "Query", "type": "table" }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"NodeDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"CpuLoad\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"MemoryLoad\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"DiskPressure\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Pods Down",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=\"PodDown\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_restarts_total) by (pod,namespace) > 0"
    }
   ]
  }
 ]
}