{
 "title": "EMA_Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instanceId",
    "query": "label_values(ema_instance_billing_numofdailyquery, instanceId)"
   }
  ]
 },
 "panels": [
  { "title": "EMA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admin Console",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_app_adminconsole_availability)",
     "function": "last",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Studio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_app_studio_availability)",
     "function": "last"
    }
   ]
  },
  {
   "title": "Sample App",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_app_sampleapp_availability)",
     "function": "last"
    }
   ]
  },
  {
   "title": "Diagnosis Data Loader",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_app_dataloader_availability)",
     "function": "last"
    }
   ]
  },
  {
   "title": "Maximo Integration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_app_maximo_availability)",
     "function": "last"
    }
   ]
  },
  {
   "title": "API Server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "column": "value", "expr": "min(ema_app_api_availability)", "function": "last" }
   ]
  },
  {
   "title": "Crawler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_app_crawler_availability)",
     "function": "last"
    }
   ]
  },
  {
   "title": "Diagnosis Engine",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_app_diagnosis_availability)",
     "function": "last"
    }
   ]
  },
  {
   "title": "Landing Page",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_app_landingpage_availability)",
     "function": "last"
    }
   ]
  },
  {
   "title": "Tenant Management DB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_service_cloudant_tenantmanagement_availability)",
     "function": "last"
    }
   ]
  },
  { "title": "EMA history", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_app_adminconsole_availability)",
     "function": "last",
     "legendFormat": "admin console"
    },
    { "expr": "min(ema_app_api_availability)", "legendFormat": "api" },
    {
     "expr": "min(ema_app_crawler_availability)",
     "legendFormat": "crawler"
    },
    {
     "expr": "min(ema_app_dataloader_availability)",
     "legendFormat": "dataloader"
    },
    {
     "expr": "min(ema_app_diagnosis_availability)",
     "legendFormat": "diagnosis engine"
    },
    {
     "expr": "min(ema_app_landingpage_availability)",
     "legendFormat": "landing page"
    },
    {
     "expr": "min(ema_app_maximo_availability)",
     "legendFormat": "maximo integration"
    },
    {
     "expr": "min(ema_app_sampleapp_availability)",
     "legendFormat": "sample app"
    },
    {
     "expr": "min(ema_app_studio_availability)",
     "legendFormat": "studio"
    },
    {
     "expr": "min(ema_app_tenantmanagement_availability)",
     "legendFormat": "tenant management"
    },
    {
     "expr": "min(ema_service_cloudant_tenantmanagement_availability)",
     "legendFormat": "tenant management db"
    }
   ]
  },
  { "title": "$instanceId", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Admin Console",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_instance_app_adminconsole_availability{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  {
   "title": "Landing Page",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_instance_app_landingpage_availability{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  {
   "title": "Sample App",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_instance_app_sampleapp_availability{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  {
   "title": "Studio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_instance_app_studio_availability{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  {
   "title": "Maximo Integration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_instance_app_maximo_availability{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  {
   "title": "Object Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_instance_service_objectStorage_availability{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  {
   "title": "Cloudant",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_instance_service_cloudant_availability{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  {
   "title": "Discovery",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "column": "value",
     "expr": "min(ema_instance_service_discovery_availability{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  { "title": "$instanceId usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Storage Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "expr": "max(ema_instance_billing_storageusage{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  {
   "title": "Num of Query(Daily)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "expr": "max(ema_instance_billing_numofdailyquery{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  },
  {
   "title": "Num of Query(Monthly)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "column": "value",
     "expr": "max(ema_instance_billing_numofmonthlyquery{instanceId=\"$instanceId\"})",
     "function": "last"
    }
   ]
  }
 ]
}