{
 "title": "Edge Computing: POD Overview",
 "description": "Edge Computing: POD Overview",
 "tags": [
  "edge-computing",
  "pods"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": "label_values(pod)" },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{pod=~\"$pod\"}, container)"
   },
   { "name": "filter", "query": "edge-computing-.*" }
  ]
 },
 "panels": [
  {
   "title": "POD Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "POD Count",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_info{pod=~\"$filter\"})"
      }
     ]
    },
    {
     "title": "Pod Status",
     "type": "graph",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg(kube_pod_status_phase{pod=~\"$filter\"}) by(pod, phase)) by(phase)",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Pod Restart",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts{pod=~\"$filter\"} or kube_pod_container_status_restarts_total{pod=~\"$filter\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "POD Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"$pod\",container_name!=\"POD\"}[2m]))"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\",container_name=~\"$container\",container_name!=\"POD\",pod_name=~\"$pod\"}[2m] ) )",
       "legendFormat": "Current: {{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container!=\"POD\"}",
       "legendFormat": "Requested: {{ container }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container!=\"POD\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod_name=~\"$pod\",container_name!=\"POD\"})"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by(container_name) (container_memory_working_set_bytes{pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"POD\"})",
       "legendFormat": "Current: {{ container_name }}"
      },
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "Requested: {{ container }}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"}",
       "legendFormat": "Limit: {{ container }}"
      }
     ]
    },
    {
     "title": "Network RX/TX Total (bytes/sec)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~\"$pod\"}[5m])) + sum(rate(container_network_receive_bytes_total{pod_name=~\"$pod\"}[5m])) "
      }
     ]
    },
    {
     "title": "POD Network",
     "type": "graph",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate (container_network_transmit_bytes_total{pod_name=~\"$pod\",interface=\"eth0\"}[5m])",
       "legendFormat": "TX : {{ pod_name }}"
      },
      {
       "expr": "rate (container_network_receive_bytes_total{pod_name=~\"$pod\",interface=\"eth0\"}[5m])",
       "legendFormat": "RX : {{ pod_name }}"
      }
     ]
    }
   ]
  }
 ]
}