{
 "title": "Edge Computing: Overview",
 "description": "Shows edge computing resource consumption",
 "tags": [ "edge-computing" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "filter", "query": "edge-computing-.*" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - max(kube_pod_start_time{pod=~\"$filter\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"$filter\",name!~\"POD\"}) / sum (machine_memory_bytes) * 100"
      }
     ]
    },
    {
     "title": "Cluster CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"$filter\"}[5m])) / sum (machine_cpu_cores) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"$filter\",name!~\"POD\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      { "expr": "sum (machine_memory_bytes)" }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"$filter\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "sum (machine_cpu_cores)" }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",pod_name=~\"$filter\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",pod_name=~\"$filter\"}[5m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",pod_name=~\"$filter\"}[5m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",pod_name=~\"$filter\"}[5m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",pod_name=~\"$filter\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",pod_name=~\"$filter\"}) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",pod_name=~\"$filter\"}) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{container_name!=\"\", pod_name=~\"$filter\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod_name=~\"$filter\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{pod_name=~\"$filter\"}[5m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{pod_name=~\"$filter\"}[5m]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"$filter\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"$filter\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",pod_name=~\"$filter\"}[5m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",pod_name=~\"$filter\"}[5m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",pod_name=~\"$filter\"}[5m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",pod_name=~\"$filter\"}[5m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod_name=~\"$filter\"}[5m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",pod_name=~\"$filter\"}[5m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  }
 ]
}