{
 "title": "Watson OpenScale",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Total Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 }, "content": "# Cluster Total Usage" },
    {
     "title": "Cluster CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster filesystem usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Cluster CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[5m]))",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Cluster memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})/1024/1024/1024",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Cluster filesystem usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})/1024/1024/1024",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  { "title": "Availability by Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "content": "# Availability by Service\nEach graph shows the number of currently \"UP\" containers for that service."
  },
  {
   "title": "Total containers ready",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_ready{namespace=\"aiopenscale\"}) / sum(kube_pod_container_info{namespace=\"aiopenscale\",container!~\".*test\",container!~\".*cleanup\"}) * 100"
    }
   ]
  },
  {
   "title": "aiopenscale kube_pod_container_status_ready",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"aiopenscale\",container!~\".*test\",container!~\".*cleanup\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_ready{namespace=\"aiopenscale\"})"
    }
   ]
  },
  {
   "title": "Request",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_pod_container_info{namespace=\"aiopenscale\",container!~\".*test\",container!~\".*cleanup\"})"
    }
   ]
  },
  {
   "title": "Total containers ready",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container!~\".*test\",container!~\".*cleanup\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Bias (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-bias\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-bias\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "ML gateway sidecar (# ready out of 3)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"ml-gateway-sidecar\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"ml-gateway-sidecar\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Common API (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-common-api\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-common-api\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Nginx (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"nginx\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"nginx\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Configuration (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-configuration-service\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-configuration-service\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Orchestration combined (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-orch-combined-service\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-orch-combined-service\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Dashboard (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-dashboard\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-dashboard\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Orchestration runtime (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-orch-runtime-service\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-orch-runtime-service\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Datamart (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-datamart\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-datamart\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Payload logging (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-payload-logging\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-payload-logging\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Etcd (# ready out of 3)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"etcd\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"etcd\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Payload logging API (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-payload-logging-api\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-payload-logging-api\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Explainability (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"explainability-service\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"explainability-service\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Redis server (# ready out of 3)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"redis\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"redis\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Fastpath (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"fast-path-service\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"fast-path-service\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Redis sentinel (# ready out of 3)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"sentinel\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"sentinel\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Feedback (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-feedback\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-feedback\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Scheduler (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-scheduling-service\"})"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-scheduling-service\"})"
    }
   ]
  },
  {
   "title": "ML gateway discovery (# ready out of 1)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"aiopenscale\",container=\"aios-ml-gateway-discovery\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=\"aiopenscale\",container=\"aios-ml-gateway-discovery\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU by Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 47 },
     "content": "# CPU by Service\n\nCPU usage for each Watson OpenScale service"
    },
    {
     "title": "Bias API CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-bias\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-bias\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "ML gateway sidecar CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"ml-gateway-sidecar\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"ml-gateway-sidecar\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Common API CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-common-api\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-common-api\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Nginx CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"nginx\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-dashboard\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Configuration CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-configuration-service\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-configuration-service\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Orchestration combined CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-orch-combined-service\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-orch-combined-service\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Dashboard CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-dashboard\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-dashboard\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Orchestration runtime CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-orch-runtime-service\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-orch-runtime-service\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Datamart CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-datamart\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-datamart\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Payload logging CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-payload-logging\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-payload-logging\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Etcd CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"etcd\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"etcd\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Payload logging API CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-payload-logging-api\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-payload-logging-api\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Explainability CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"explainability-service\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"explainability-service\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Redis server CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"redis\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"redis\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Fastpath CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"fast-path-service\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"fast-path-service\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Redis sentinel CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"sentinel\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"sentinel\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Feedback CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-feedback\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-feedback\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Scheduler CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-scheduling-service\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-scheduling-service\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "ML gateway discovery CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{namespace=\"aiopenscale\",container_name=\"aios-ml-gateway-discovery\"}[5m]))",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"aiopenscale\",container=\"aios-ml-gateway-discovery\"})",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory by Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 48 },
     "content": "# Memory by Service\n\nMemory usage for each Watson OpenScale service"
    },
    {
     "title": "Bias memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-bias\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-bias\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "ML gateway sidecar memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"ml-gateway-sidecar\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"ml-gateway-sidecar\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Common API memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-common-api\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-common-api\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Nginx memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"nginx\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"nginx\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Configuration memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-configuration-service\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-configuration-service\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Orchestration combined memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-orch-combined-service\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-orch-combined-service\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Dashboard memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-dashboard\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-dashboard\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Orchestration runtime memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-orch-runtime-service\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-orch-runtime-service\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Datamart memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-datamart\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-datamart\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Payload logging memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-payload-logging\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-payload-logging\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Etcd memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"etcd\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"etcd\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Payload logging API memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-payload-logging-api\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-payload-logging-api\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Explainabilty memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"explainability-service\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"explainability-service\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Redis server memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"redis\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"redis\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Fastpath memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"fast-path-service\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"fast-path-service\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Redis sentinel memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"sentinel\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"sentinel\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Feedback memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-feedback\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-feedback\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Scheduler memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-scheduling-service\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-scheduling-service\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "ML gateway discovery memory usage",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"aiopenscale\",container_name=\"aios-ml-gateway-discovery\"})/1024/1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"aiopenscale\",container=\"aios-ml-gateway-discovery\"})/1024/1024",
       "legendFormat": "Limit"
      }
     ]
    }
   ]
  },
  { "title": "Filesystem by Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
   "content": "# Filesystem by Service\nFilesystem usage for each Watson OpenScale service"
  },
  {
   "title": "Bias filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container_name=\"aios-bias\"})/1024/1024"
    }
   ]
  },
  {
   "title": "ML gateway sidecar filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"ml-gateway-sidecar\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Common API filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-common-api\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Nginx filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"nginx\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Configuration filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-configuration-service\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Orchestration combine filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-orch-combined-service\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Dashboard filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-dashboard\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Orchestration runtime filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-orch-runtime-service\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Datamart filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-datamart\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Payload logging filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-payload-logging\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Etcd filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"etcd\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Payload logging API filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-payload-logging-api\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Explainability filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"explainability-service\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Redis server filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"redis\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Fastpath filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"fast-path-service\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Redis sentinel filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"sentinel\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Feedback filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-feedback\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Scheduler filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-scheduling-service\"})/1024/1024"
    }
   ]
  },
  {
   "title": "ML gateway discovery filesystem usage",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"aiopenscale\",container_name=\"aios-ml-gateway-discovery\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Images and Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Images and versions",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sort(kube_pod_container_info{namespace=\"aiopenscale\",container!~\".*test\",container!~\".*cleanup\"})"
      }
     ]
    }
   ]
  }
 ]
}