{
 "title": "EA_Grouped_Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(eventCount)" }
   ]
  },
  {
   "title": "Total Events V's Event Viewer Entries (5 Min Aggregation)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(idelta(eventCount[5m]))", "legendFormat": "Total Number of Events" },
    {
     "expr": "sum(idelta(ungroupedEvents[5m])) + sum(idelta(EAGroupsAppliedTotal[5m])) + sum(idelta(EASupergroupsAppliedTotal[5m]))",
     "legendFormat": "Event Viewer Rows"
    }
   ]
  },
  {
   "title": "Total Events V's Event Viewer Entries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(eventCount[5m]))",
     "legendFormat": "Total Number of Events"
    },
    {
     "expr": "sum(max_over_time(ungroupedEvents[5m])) + sum(max_over_time(EAGroupsAppliedTotal[5m])) + sum(max_over_time(EASupergroupsAppliedTotal[5m]))",
     "legendFormat": "Event Viewer Rows"
    }
   ]
  },
  {
   "title": "Event Viewer Events (un-grouped)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ungroupedEvents)" }
   ]
  },
  {
   "title": "Incidents (single group)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(EAGroupsAppliedTotal)" }
   ]
  },
  {
   "title": "Incidents (super groups)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(EASupergroupsAppliedTotal)", "legendFormat": "Super Groups Count" }
   ]
  },
  {
   "title": "Percentage Reduction Average",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 16, "x": 3, "y": 10 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - ((sum(EASupergroupsAppliedTotal)+sum(EAGroupsAppliedTotal)+sum(ungroupedEvents))/sum(eventCount)))*100",
     "legendFormat": "Super Groups Count"
    }
   ]
  },
  {
   "title": "TOP 20 Correlation Groups/Scopes",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(20,sum(actionCount) by (groupid, group_size))"
    }
   ]
  },
  {
   "title": "Top 20 Occurring Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "topk(20, sum(actionCount) by (eventId))"
    }
   ]
  }
 ]
}