{
 "title": "IIRA",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DATA ASSETS IMPORT JOBS DURATIONS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "jobs_durations_seconds_sum{iira_orchestrator=\"data_assets_import\"}",
     "legendFormat": "DATA ASSETS IMPORT JOB DURATIONS"
    }
   ]
  },
  {
   "title": "GLOSSARY IMPORT JOBS DURATIONS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "jobs_durations_seconds_sum{iira_orchestrator=\"glossary_import\"}",
     "legendFormat": "GLOSSARY IMPORT JOB DURATIONS"
    }
   ]
  },
  {
   "title": "PROJECT EXPORT JOBS DURATIONS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "jobs_durations_seconds_sum{iira_orchestrator=\"mappings_export\"}",
     "legendFormat": "PROJECT EXPORT JOBS DURATIONS"
    }
   ]
  },
  {
   "title": "Number of Failed Jobs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "jobs_results{job_function=\"categoriesImportJob\",job_result=\"Fail\"}",
     "legendFormat": "FAILED CATEGORY IMPORT JOBS"
    },
    {
     "expr": "jobs_results{job_function=\"termsImportJob\",job_result=\"Fail\"}",
     "legendFormat": "FAILED TERM IMPORT JOBS"
    },
    {
     "expr": "jobs_results{job_function=\"glossaryImportJob\",job_result=\"Fail\"}",
     "legendFormat": "FAILED GLOSSARY IMPORT JOBS"
    },
    {
     "expr": "jobs_results{job_function=\"exportProjectMappings\",job_result=\"Fail\"}",
     "legendFormat": "FAILED EXPORT PROJECT JOBS"
    }
   ]
  },
  {
   "title": "Number of Succesful jobs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "jobs_results{job_function=\"categoriesImportJob\",job_result=\"Success\"}",
     "legendFormat": "CATEGORY IMPORT"
    },
    {
     "expr": "jobs_results{job_function=\"glossaryImportJob\",job_result=\"Success\"}",
     "legendFormat": "GLOSSARY IMPORT"
    },
    {
     "expr": "jobs_results{job_function=\"termsImportJob\",job_result=\"Success\"}",
     "legendFormat": "TERMS IMPORT"
    },
    {
     "expr": "jobs_results{job_function=\"exportProjectMappings\",job_result=\"Success\"}",
     "legendFormat": "EXPORT PROJECT"
    },
    {
     "expr": "jobs_results{job_function=\"dataAssetsImportJob\",job_result=\"Success\"}",
     "legendFormat": "DATA ASSETS IMPORT"
    }
   ]
  },
  {
   "title": "Number of Jobs Submitted",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jobs_durations_seconds_count{iira_orchestrator=\"glossary_import\"}",
     "legendFormat": "Glossary Import Jobs Submitted"
    },
    {
     "expr": "jobs_durations_seconds_count{iira_orchestrator=\"data_assets_import\"}",
     "legendFormat": "Data Assets Import Jobs Submitted"
    },
    {
     "expr": "jobs_durations_seconds_count{iira_orchestrator=\"mappings_export\"}",
     "legendFormat": "Export Jobs Submitted"
    }
   ]
  },
  {
   "title": "T2T Mappings Durations",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "ml_mappings_durations_seconds_sum{iira_orchestrator=\"t2t_mappings\"}",
     "legendFormat": "T2T Mappings Durations"
    }
   ]
  },
  {
   "title": "T2A Mappings Durations",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "ml_mappings_durations_seconds_sum{iira_orchestrator=\"t2a_mappings\"}",
     "legendFormat": "T2A Mappings Durations"
    }
   ]
  },
  {
   "title": "Number of Mappings Done",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "ml_mappings_durations_seconds_count{iira_orchestrator=\"t2a_mappings\"}",
     "legendFormat": "T2A Mappings Requests"
    },
    {
     "expr": "ml_mappings_durations_seconds_count{iira_orchestrator=\"t2t_mappings\"}",
     "legendFormat": "T2T Mappings Requests"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none", "label": "go routines" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"localhost:8080\",job=\"orc\"}",
     "legendFormat": "GO ROUTINES"
    }
   ]
  }
 ]
}