{
 "title": "Capacity and Utilization",
 "tags": [
  "kubernetes",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Pods Per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(kubelet_running_pod_count)", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Transmit and Receive Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes sent and received" }
   ],
   "targets": [
    {
     "expr": "node_network_receive_bytes_total",
     "legendFormat": "{{ instance }} receive"
    },
    {
     "expr": "node_network_transmit_bytes_total",
     "legendFormat": "{{ instance }} transmit"
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total[5m])",
     "legendFormat": "{{device}} Receive Errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total[5m])",
     "legendFormat": "{{device}} Transmit Errors"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory Used %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent", "label": "Memory Used" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{ instance }} memory used"
    }
   ]
  },
  {
   "title": "Load Average (15 mins)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{instance}} 15min" }
   ]
  }
 ]
}