{
 "title": "Metrics Dashboard",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "Registry", "query": "label_values(image)" }
  ]
 },
 "panels": [
  { "title": "Resources Used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes)/1024/1024/1024"
    }
   ]
  },
  { "title": "Number of K8s Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Missing Replicas by Deployment",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment!=\"\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "Deployments Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas)"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready) + sum(kube_pod_status_phase) + sum(kube_pod_status_scheduled)"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running) + sum(kube_pod_container_status_ready) + sum(kube_pod_container_status_waiting)+ sum(kube_pod_container_status_terminated)"
    }
   ]
  },
  {
   "title": "Total Container Restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total)"
    }
   ]
  },
  { "title": "Pod Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Number of Pods per Namespace",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace!=\"\", namespace=~\"^$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace!=\"\", namespace=~\"^$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_status_scheduled{namespace!=\"\", namespace=~\"^$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace!=\"\", namespace=~\"^$namespace\"}) by (namespace) + sum(kube_pod_status_phase{namespace!=\"\", namespace=~\"^$namespace\"}) by (namespace) + sum(kube_pod_status_scheduled{namespace!=\"\", namespace=~\"^$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Missing Pods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pod Count by Node",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count({node!=\"\", pod!=\"\"}) by(node)"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count({phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Number of Pod Restarts per Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total) by (pod)"
    }
   ]
  },
  { "title": "CrashLoopBackOff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total Pods with CrashLoopBackOff",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"})"
    }
   ]
  },
  {
   "title": "CrashLoopBackOff by Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}) by(container)"
    }
   ]
  },
  {
   "title": "CrashLoopBackOff by Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{reason=~\"CrashLoopBackOff\",namespace=~\"$namespace\"}) by(namespace)"
    }
   ]
  }
 ]
}