{
 "title": "Workers Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Worker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(irate(node_cpu_seconds_total[5m])) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Memory Utilization %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)((node_memory_Active_bytes / node_memory_MemTotal_bytes)* 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Nodes 15,5,1 min Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{instance}} 15min" },
    { "expr": "node_load5", "legendFormat": "{{instance}} 5min" },
    { "expr": "node_load1", "legendFormat": "{{instance}} 1min" }
   ]
  },
  { "title": "Disk Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Disk Used %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent", "label": "Percentage Used" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Total Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total[5m])",
     "legendFormat": "{{ instance }} Reads Completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total[5m])",
     "legendFormat": "{{ instance }} Writes Completed"
    }
   ]
  },
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Read/Write Bytes per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[5m])",
     "legendFormat": "{{instance}} read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[5m])",
     "legendFormat": "{{instance}} write bytes"
    }
   ]
  },
  {
   "title": "Transmit Bytes Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "{{device}} Transmit bytes"
    }
   ]
  },
  {
   "title": "Receive Bytes Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[5m])",
     "legendFormat": "{{device}} Receive bytes"
    }
   ]
  }
 ]
}