{
 "title": "IBM Aspera High-Speed Transfer Server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transfer Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "((aspera_hsts_finished_sessions - aspera_hsts_failed_sessions) / aspera_hsts_finished_sessions)*100"
    }
   ]
  },
  {
   "title": "Failed Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "aspera_hsts_failed_sessions" }
   ]
  },
  {
   "title": "Successful Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aspera_hsts_finished_sessions-aspera_hsts_failed_sessions"
    }
   ]
  },
  {
   "title": "Active Transfer Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aspera_hsts_transferring_sessions"
    }
   ]
  },
  {
   "title": "Transfer Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aspera_hsts_failed_sessions", "legendFormat": "Failed" },
    {
     "expr": "aspera_hsts_finished_sessions - aspera_hsts_failed_sessions",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Aggregate Transfer Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    { "expr": "aspera_hsts_actual_rate_kbps", "legendFormat": "Transfer Rate" }
   ]
  },
  {
   "title": "Active Transfer Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aspera_hsts_transferring_sessions",
     "legendFormat": "Active Sessions"
    }
   ]
  }
 ]
}