#!/bin/bash
#
#################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corp. 2018.  All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with
# IBM Corp.
#################################################################
#
# You need to run this once per cluster
#
# Example:
#     ./Cleanup.sh [ -n  <namespace> ] [--all] [ --force ]
#

FORCE=""
ALL=""

usage() {
  echo "Usage: $0 [-n <NAMESPACE>] [ --all ] [ --force ]"
  exit 1
}
# Delete pull secret

remove_crfin() {
  crd="$1"
  crdexists=$(kubectl get crd $crd 2>/dev/null)
  if [ "X$crdexists" == "X" ]; then
    return
  fi
  echo "Check for remaining custom resources of type $crd"
  for cr in $(kubectl get -n $NAMESPACE $crd -o name)
  do
    echo "Removing finalizers from $cr"
    kubectl patch -n $NAMESPACE $cr --type json -p='[{"op": "remove", "path": "/metadata/finalizers"}]' 
    echo "Removing $cr"
    kubectl delete -n $NAMESPACE $cr
  done
  echo "Deleting $crd"
  kubectl patch crd $crd --type json -p='[{"op": "remove", "path": "/metadata/finalizers"}]'
  kubectl delete crd $crd
}

kuberm() {
  type="$1"
  name="$2"
 
  obj=$(kubectl get $type $name -o name 2>/dev/null)
  if [ "X$obj" != "X" ]; then
    kubectl delete $obj
  fi
}

set_namespace()
{
  NAMESPACE="$1"
  ns=$(kubectl get namespace $NAMESPACE -o name 2>/dev/null)
  if [ "X$ns" == "X" ]; then
    echo "ERROR: Invalid namespace $NAMESPACE"
    exit 1
  fi
}

if [ "X$WATCH_NAMESPACE" == "X" ]; then
  NAMESPACE=$(oc project | sed -e 's/^[^"]*"//' -e 's/".*$//')
else
  NAMESPACE="$WATCH_NAMESPACE"
fi

while true
do
  arg="$1"
  shift
  if [ "X$arg" == "X" ]; then
     break
  fi
  case $arg in
  -n)
    set_namespace "$1"
    shift
    ;;
  --force)
     FORCE="yes"
     ;;
  --all)
     ALL="yes"
     ;;
  *)
     echo "ERROR: invalid argument $arg"
     usage
     exit 1
  esac
done

remove_crfin iscsequences.isc.ibm.com
remove_crfin redis.isc.ibm.com
remove_crfin couchdb.isc.ibm.com
remove_crfin etcd.isc.ibm.com
remove_crfin minio.isc.ibm.com
remove_crfin oidcclient.isc.ibm.com

# generated by default by middleware operator
kubectl delete secret -n $NAMESPACE isc-jwt isc-helm-account 2>/dev/null

# Remove license
kuberm configmap ibm-security-foundations-prod-license

kuberm crd mappings.getambassador.io


for role in pgo-backrest-role \
            pgo-role
do
   kuberm role $role
done

for rolebinding in pgo-backrest-role-binding \
                   pgo-role-binding 
do
   kuberm rolebinding $rolebinding
done

for sa in ambassador \
   ibm-isc-application \
   ibm-isc-operators \
   pgo-backrest \
   postgres-operator
do
   kuberm serviceaccount $sa
done

kuberm clusterrole ibm-isc-operators
kuberm clusterrolebinding ibm-isc-operators
  

if [ "X$ALL" != "X" ]; then
# Remove openwhisk labels
  kubectl label nodes --all openwhisk-role-

  kuberm serviceaccount ibm-dba-ek-isc-cases-elastic-bai-psp-sa
  kuberm secret ibm-isc-pull-secret
  kuberm scc ibm-isc-scc
fi
