{
 "title": "IBM Event Streams Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "rn", "label": "Release", "query": "label_values(release)" },
   {
    "name": "kafka",
    "label": "kafka",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate_value{kubernetes_namespace=~\"$ns\"},  kafka)"
   }
  ]
 },
 "panels": [
  { "title": "Event Streams Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Status",
   "type": "graph",
   "description": "The status of the Event Streams pods, all should be in the running state with no unready pods ideally. Pods may become unready for short periods of time if they are busy, but if this happens often there may be a bottlenecking issue",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Pod Count" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$ns\", pod=~\"$rn-.*\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$ns\", pod=~\"$rn-.*\", condition=\"false\"})",
     "legendFormat": "Unready"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "description": "Tracks the total restarts for all containers in a pod, not displaying those with 0 restarts. If the number of restarts is rising there is a problem with the install of Event Streams",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$ns\", pod=~\"$rn-.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "UnderReplicatedPartitions: In a healthy cluster, the number of in sync replicas (ISRs) should be exactly equal to the total number of replicas. If partition replicas fall too far behind their leaders, the follower partition is removed from the ISR pool, and you should see a corresponding increase in IsrShrinksPerSec. Since Kafka’s high-availability guarantees cannot be met without replication, investigation is certainly warranted should this metric value exceed zero for extended time periods.",
   "gridPos": { "h": 12, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "singlestat",
   "description": "ActiveControllerCount: The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
    }
   ]
  },
  { "title": "Kafka Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Byte rate into kafka",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesinpersec_alltopics_oneminuterate{kubernetes_namespace=\"$ns\", release=\"$rn\"}",
     "legendFormat": "Kafka-{{ kafka }}"
    }
   ]
  },
  {
   "title": "Byte rate out of kafka",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesoutpersec_alltopics_oneminuterate{kubernetes_namespace=\"$ns\", release=\"$rn\"}",
     "legendFormat": "Kafka-{{ kafka }}"
    }
   ]
  },
  {
   "title": "CPU for kafka-$kafka",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 25 },
   "repeat": "kafka",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{kubernetes_namespace=\"$ns\", image!=\"\",container_name!=\"POD\",pod_name=~\"$rn-.*-kafka-sts-$kafka\"}[2m] ) )",
     "legendFormat": "{{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$ns\", pod=~\"$rn-.*-kafka-sts-$kafka\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  { "title": "Topics & Partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Global Partitions Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
    }
   ]
  },
  {
   "title": "Global Topic Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "OfflinePartitionsCount (controller only): This metric reports the number of partitions without an active leader. Because all read and write operations are only performed on partition leaders, a non-zero value for this metric should be alerted on to prevent service interruptions. Any partition without an active leader will be completely inaccessible, and both consumers and producers of that partition will be blocked until a leader becomes available.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{kubernetes_namespace=~\"$ns\", release=~\"$rn\"})"
    }
   ]
  }
 ]
}