{
 "title": "mq_grafana_dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Queue Managers Running",
   "type": "singlestat",
   "description": "# Queue Managers Running\n\nPercentage of Queue Manager pods in a *ready* state",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_pod_status_ready{pod=~\".*ibm-mq-0\", condition=\"true\"}) / sum(kube_pod_info{pod=~\".*ibm-mq-0\"})) * 100"
    }
   ]
  },
  {
   "title": "Message Failure Rate",
   "type": "graph",
   "description": "# Message Failure Rate\n\nRate of `MQGET` & `MQPUT` command failures",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ibmmq_qmgr_failed_mqget_total[5m])",
     "legendFormat": "MQGET {{qmgr}}"
    },
    {
     "expr": "rate(ibmmq_qmgr_failed_mqput_total[5m])",
     "legendFormat": "MQPUT {{qmgr}}"
    },
    {
     "expr": "rate(ibmmq_qmgr_failed_mqput1_total[5m])",
     "legendFormat": "MQPUT1 {{qmgr}}"
    }
   ]
  },
  {
   "title": "MQPUT Success Rate",
   "type": "graph",
   "description": "# MQPUT Success Rate\n\nRate of successful `MQPUT` commands",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ibmmq_qmgr_mqput_mqput1_total[5m])",
     "legendFormat": "MQPUT {{qmgr}}"
    }
   ]
  },
  {
   "title": "Maximum CPU Load",
   "type": "singlestat",
   "description": "# Maximum CPU Load\n\nMaximum CPU Load of all Queue Managers",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(ibmmq_qmgr_cpu_load_one_minute_average_percentage)",
     "legendFormat": "{{qmgr}}"
    }
   ]
  },
  {
   "title": "Maximum RAM Usage",
   "type": "singlestat",
   "description": "# Maximum Ram Usage\n\nMaximum RAM Usage of all Queue Managers",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - max(ibmmq_qmgr_ram_free_percentage)"
    }
   ]
  },
  {
   "title": "Maximum Log Usage",
   "type": "singlestat",
   "description": "# Maximum Log Usage\n\nMaximum Log system usage of all Queue Managers",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(max(ibmmq_qmgr_log_file_system_in_use_bytes) / max(ibmmq_qmgr_log_file_system_max_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Log Write Latency",
   "type": "singlestat",
   "description": "# Log Write Latency\n\nMaximum Log Write Latency of all Queue Managers",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ibmmq_qmgr_log_write_latency_seconds)"
    }
   ]
  },
  {
   "title": "FDC Errors",
   "type": "singlestat",
   "description": "# FDC Errors\n\nNumber of FDC files across all Queue Managers",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(ibmmq_qmgr_fdc_files)" }
   ]
  },
  {
   "title": "MQ Connections",
   "type": "singlestat",
   "description": "# MQ Connections\n\nNumber of MQ Connections accross all Queue Managers",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ibmmq_qmgr_mqconn_mqconnx_total)"
    }
   ]
  }
 ]
}