{
 "title": "mq_qm_grafana_dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "qmgr", "label": "Queue Manager", "query": "${VAR_QMGR}" }
  ]
 },
 "panels": [
  {
   "title": "Message Failure Rate",
   "type": "graph",
   "description": "# Message Failure Rate\n\nRate of `MQGET` & `MQPUT` command failures",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ibmmq_qmgr_failed_mqget_total{qmgr=\"$qmgr\"}[5m])",
     "legendFormat": "MQGET {{qmgr}}"
    },
    {
     "expr": "rate(ibmmq_qmgr_failed_mqput_total{qmgr=\"$qmgr\"}[5m])",
     "legendFormat": "MQPUT {{qmgr}}"
    },
    {
     "expr": "rate(ibmmq_qmgr_failed_mqput1_total{qmgr=\"$qmgr\"}[5m])",
     "legendFormat": "MQPUT1 {{qmgr}}"
    }
   ]
  },
  {
   "title": "MQPUT Success Rate",
   "type": "graph",
   "description": "# MQPUT Success Rate\n\nRate of successful `MQPUT` commands",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ibmmq_qmgr_mqput_mqput1_total{qmgr=\"$qmgr\"}[5m])",
     "legendFormat": "MQPUT {{qmgr}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "description": "# CPU Load\n\nCPU Load of Queue Manager",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ibmmq_qmgr_cpu_load_one_minute_average_percentage{qmgr=\"$qmgr\"}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "singlestat",
   "description": "# Ram Usage\n\nRAM Usage of Queue Manager",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - ibmmq_qmgr_ram_free_percentage{qmgr=\"$qmgr\"}"
    }
   ]
  },
  {
   "title": "Log System Usage",
   "type": "singlestat",
   "description": "# Log Usage\n\nLog system usage of Queue Manager",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(ibmmq_qmgr_log_file_system_in_use_bytes{qmgr=\"$qmgr\"} / ibmmq_qmgr_log_file_system_max_bytes{qmgr=\"$qmgr\"}) * 100"
    }
   ]
  },
  {
   "title": "Log Write Latency",
   "type": "singlestat",
   "description": "# Log Write Latency\n\nLog Write Latency of Queue Manager",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "ibmmq_qmgr_log_write_latency_seconds{qmgr=\"$qmgr\"}"
    }
   ]
  },
  {
   "title": "FDC Errors",
   "type": "singlestat",
   "description": "# FDC Errors\n\nNumber of FDC files on Queue Manager",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ibmmq_qmgr_fdc_files{qmgr=\"$qmgr\"})"
    }
   ]
  },
  {
   "title": "MQ Connections",
   "type": "singlestat",
   "description": "# MQ Connections\n\nNumber of MQ Connections to/from Queue Manager",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ibmmq_qmgr_mqconn_mqconnx_total{qmgr=\"$qmgr\"}"
    }
   ]
  }
 ]
}