{
 "title": "mq_usage_grafana_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort(ibmmq_qmgr_cpu_load_one_minute_average_percentage)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sort(100 - ibmmq_qmgr_ram_free_percentage)"
    }
   ]
  },
  {
   "title": "Log Usage",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sort((ibmmq_qmgr_log_file_system_in_use_bytes/ibmmq_qmgr_log_file_system_max_bytes)*100)"
    }
   ]
  }
 ]
}