{
 "title": "DataPower Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Graphs CPU usage as seen by DataPower",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "% Utilization" }
   ],
   "targets": [
    {
     "expr": "dpStatusSystemUsage2TableCPU",
     "legendFormat": "{{kubernetes_pod_name}}-Task{{dpStatusSystemUsage2TableTaskID}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "% Utilization" }
   ],
   "targets": [
    {
     "expr": "dpStatusSystemUsage2TableMemory",
     "legendFormat": "{{kubernetes_pod_name}}-Task{{dpStatusSystemUsage2TableTaskID}}"
    }
   ]
  },
  {
   "title": "Work List Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Work items" }
   ],
   "targets": [
    {
     "expr": "dpStatusSystemUsage2TableWorkList",
     "legendFormat": "{{kubernetes_pod_name}}-Task{{dpStatusSystemUsage2TableTaskID}}"
    }
   ]
  },
  {
   "title": "TCP Connections Established",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    { "expr": "dpStatusTCPSummaryestablished", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  }
 ]
}