{
 "title": "Resiliency Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "Container",
    "label": "container",
    "query": "label_values(kube_pod_container_info, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"$Container\",namespace=\"$Namespace\"}[2m])"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"$Container\",namespace=\"$Namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total Namespace CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Memory per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"$Container\",namespace=\"$Namespace\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"$Container\",namespace=\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Total Namespace Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{container=\"$Container\",namespace=\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Total Cluster CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[2m]))"
    }
   ]
  },
  {
   "title": "Total Cluster Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes)"
    }
   ]
  }
 ]
}